---
apiVersion: v1
kind: ReplicationController
metadata:
  # here is the name of the replication controller (RC)
  name: kubapp
spec:
  replicas: 3
  # what pods the RC is operating on
  selector:
    app: kubapp
  # the pod template for creating new pods
  template:
    metadata:
      labels:
        app: kubapp
    spec:
      containers:
      - name: kubapp
        image: evalle/kubapp
...
